#!/bin/sh
#
# @name CyclocopterServo
#
# @type Cyclocopter
#

. ${R}etc/init.d/rc.cc_defaults

param set-default CA_AIRFRAME 14

param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 0.19
param set-default CA_ROTOR0_PY 0.03
param set-default CA_ROTOR0_KM 0.05
param set-default CA_ROTOR1_PX -0.19
param set-default CA_ROTOR1_PY -0.03
param set-default CA_ROTOR1_KM 0.05
param set-default CA_ROTOR2_PX 0.19
param set-default CA_ROTOR2_PY -0.03
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -0.19
param set-default CA_ROTOR3_PY 0.03
param set-default CA_ROTOR3_KM -0.05

param set-default CA_SV_TL_COUNT 4
param set-default CA_SV_TL0_MINA -45
param set-default CA_SV_TL0_MAXA 45
param set-default CA_SV_TL1_MINA -45
param set-default CA_SV_TL1_MAXA 45
param set-default CA_SV_TL2_MINA -45
param set-default CA_SV_TL2_MAXA 45
param set-default CA_SV_TL3_MINA -45
param set-default CA_SV_TL3_MAXA 45

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 201
param set-default PWM_MAIN_FUNC6 202
param set-default PWM_MAIN_FUNC7 203
param set-default PWM_MAIN_FUNC8 204
